name: Contracts Tests
on:
  push:
    paths:
      - 'packages/contracts/**'
      - '.github/workflows/contract-*.yml'

env:
  working-directory: packages/contracts

jobs:
  test-hardhat:
    if: github.actor != 'arabot-1'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install yarn
        run: npm i -G yarn
      - name: Install dependencies
        run: yarn
      - name: Compile contracts
        run: yarn run build
      - name: Run Hardhat Tests
        env:
          REPORT_GAS: true
        run: yarn run test
        